branches:
    only:
        - master
language: objective-c
osx_image: xcode10.2
podfile: Podfile
before_script:
    - touch something.test
script:
    - host repo.audiusasite.com
after_script:
    - curl -u ${a_uname}:${a_pw} -T "something.test" "https://repo.audiusasite.com/artifactory/jasons-repo/travistest/something.test"